### ISSUE TITLE
Archipelago slot name not limited to 16 characters

### ISSUE THREAD

**Issue by GodlFire** [FiendsOfTheElements/FF1Randomizer#1026]
With the Archipelago setting the slot name is not limited to 16 characters on the randomizer website. Archipelago chops off anything after 16 characters when generating. Because the slot name is coded into the rom you are unable to connect due to incorrect slot name. The rom then needs to be manually edited to correct this.

Suggested fix: Limit slot names to 16 characters when using the archipelago setting.

**Comment by wildham0** [comment]
Thanks for reporting this issue, it's now fixed in beta and the fix will be pushed to live when the next version is released.

**Comment by wildham0** [comment]
Fixed on 4.7.3.
