### ISSUE TITLE
Custom Chaos Rush Goal freezes generation at 16/26

### ISSUE THREAD

**Issue by chrono1313** [FiendsOfTheElements/FF1Randomizer#1028]
This working link will successfully generate a ROM with 1 orb required. If you set the Orb requirement to 0, the ROM generation will always freeze at 16/26 "Finalizing". 

Working 1 ORB required: https://4-7-2.finalfantasyrandomizer.com/?s=15FCC53E&f=mAzCRVkgnLRmfb3C8W7GkhorqFowY8NVjS2fYzmJTS96e9wRKKXFHncssrqkOxH-6EG2A7t8gJhTMCwh0dta2182hzroBhyM91Mkm7TWjPZLA4UctrUg15qTv-OYx0WYOedJ07Nl7-.ews8wctBPTlG2ezW6xnwbbNwehPD

Non-working link that will always freeze (no Orb or shard). 
Also note that Shard Hunt cannot be selected, though I suspect that is the same issue as the freeze:
https://4-7-2.finalfantasyrandomizer.com/?s=15FCC53E&f=mAzCRVkgnLRmfLhQN1CsjgKLoApKy.kS5HqmXdFJ4DHTxu3kqpw7u0HtJj.gOxH-6EG2A7t8gJhTMCwh0dta2182hzroBhyM91Mkm7TWjPZLA4UctrUg15qTv-OYx0WYOedJ07Nl7-.ews8wctBPTlG2ezW6xnwbbNwehPD

**Comment by wildham0** [comment]
Fixed on 4.7.3, thanks for your bug report.
