### ISSUE TITLE
Element Icons displayed incorrectly in Status Menu (Weapon, Armor, Magic)

### ISSUE THREAD

**Issue by Rudicron** [FiendsOfTheElements/FF1Randomizer#1034]
With the Shop Information Icons flag on, when examining a Weapon, Armor, or Spell in the Status Menu, any elemental or status effect properties of that item are not properly displayed as icons, instead the icons are displayed as portions of the PoisonStoneslMAGICFIGHTDRINK sprites.

This issue first appeared in version 4.7.0.

Example Screenshots, using the following RomInfo:
FFRInfo
Seed: 7D3D7444
OW Seed: none
Res. Pack Hash: none
Flags: 22GobENvW7HOHl.uNIs-XKKFkXtZuEykS.CaC1dv4RLYkep9245CSsowktgiB217cXwZbgwrXatygh649NRUuLvH6vY9nlFGA7pqim01Yh588SUjgnxomJtP3NXVQnMayb-JoB3Qw.xoagiebfuDAJjQdlsST5Or.R2dcvB
Version: 4-7-4

Weapon:
![FFR_7D3D7444_FTGATKSF_007](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/35be3a3e-e988-41f2-a37b-abe82a97699c)

Armor:
![FFR_7D3D7444_FTGATKSF_002](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/aaed3ec9-7a03-4622-89bc-a36c04061469)

Spell:
![FFR_7D3D7444_FTGATKSF_006](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/d0ea2800-044e-4ab0-ad64-84ec39b5ffa7)

Compare to appearance in the Shop, where Icons are displayed as expected:
![FFR_7D3D7444_FTGATKSF_001](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/0d5a9406-c820-42a4-b5a1-775f9ca486c8)

### Expected Behavior

When examining a Weapon, Armor, or Spell in the Status Menu, any elemental or status properties of that item should be displayed as icons. This was the case in 4.6.4.

The three screenshots below use the following RomInfo
FFRInfo
Seed: 3BA6F550
Flags: mMZpMoO-2zLEdcOa2gbC-lk5cG8wyPCXoJQ5gEJlegIwIYrA8lezB1ZKXjv2CfAi0S-o2dq58bX-4aO5aMaWDPojtbJk5RvX9Ibe369aGxX80y-5Mob6058I3fjAP.qiFGF8bs6mFiH3OQkkHA87.H64kDxTBbBFA6LKr_DB98FB26795C3C73AB826DB7546DB84D_00
Version: 4-6-4

Weapon:
![FFR_3BA6F550_mMZpMoO-2zLEdyoxcGr0RbkyQKUYloYxcRB0N6RVLI3srNazLuhyoMKpsev2CfAi0S-o2dq58bX-4aO5aMaWDPojtbJk5RvX9Ibe369aGxX80y-5Mob6058I3fjAP qiFGF8bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_008](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/e8913246-3186-43f7-8669-0dc97d6526a5)

Armor:
![FFR_3BA6F550_mMZpMoO-2zLEdyoxcGr0RbkyQKUYloYxcRB0N6RVLI3srNazLuhyoMKpsev2CfAi0S-o2dq58bX-4aO5aMaWDPojtbJk5RvX9Ibe369aGxX80y-5Mob6058I3fjAP qiFGF8bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_005](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/25dd0924-ca15-46c0-8127-452391216a31)

Spell:
![FFR_3BA6F550_mMZpMoO-2zLEdyoxcGr0RbkyQKUYloYxcRB0N6RVLI3srNazLuhyoMKpsev2CfAi0S-o2dq58bX-4aO5aMaWDPojtbJk5RvX9Ibe369aGxX80y-5Mob6058I3fjAP qiFGF8bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_006](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/94f34fb8-178a-4a84-ab4b-be0f2ce3f486)

### Further Information

The array of element icons is showing up in the PPU pattern memory, but not in the place where the info window routine is looking for it; as illustration, here's a screenshot from the Tile Viewer in Mesen. 

This screenshot shows the tiles while the game is in the menu. (using the 4.7.4 rom detailed above)
![Tiles in Menu](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/18b337ec-69a3-446b-8253-e24ec3ecb441)

and these are the tiles when in the shop.
![Tiles in shop](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/17179485-e0ca-4000-a00c-276d91f5fbdb)

For comparison, here's the tiles while in the menu, but with the 4.6.4 rom (again detailed above)
![4 6 4  Tiles in Menu](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/e4030f00-b71d-4d92-82df-ea055ade3bb0)

and the tiles in the shop on 4.6.4.
![4 6 4 - Tiles in shop](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/978c2bf6-91d9-447f-9073-cd23de55b9e2)

### Speculation
What this leads me to believe is that either the routine that copies the icon array when the menu is opened is copying it to the wrong address, or the infobox display routine needs to know the actual location of the icon array.

**Comment by wildham0** [comment]
Fixed in 4.8.0

**Comment by Rudicron** [comment]
Thanks, this looks great! 
For clarification, 69ea9b16dc04f16753f2a6462332a577ae564dce was the specific commit that resolved this issue.

Here's some screenshots for confirmation, using the following RomInfo:
FFRInfo
Seed: AFEE743C
OW Seed: none
Res. Pack Hash: none
Flags: etdy-wV11xweQEInyuyZIBBkGTXp--tydQuTcA5GvlM0JqUnEB3bQbYm7USFziJGHCQvAuBrxyHozsSfRgGxHjXyn3.-15tfz3pZd0MbzDbCGYpuMJ2DYeUW3KJovNY2-nwCDTD0Bk3lZe944YTn3IOjXqJ2pR1YzsQEfc9lNAp
Version: beta-7d8d80f

Equipment:
![FFR_AFEE743C_TNAKNGGX_000](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/c55f52bf-9dbc-4772-8ceb-5a71c81acb47)

Spell (Elements):
![FFR_AFEE743C_TNAKNGGX_001](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/68fbd106-29fa-4844-97ab-b0aa5f330fd6)

Spell (Status):
![FFR_AFEE743C_TNAKNGGX_002](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/14276837/fabb42a7-97d3-4436-8826-ba8a2354b8f8)
