### ISSUE TITLE
[4.7.2] Spoiler log may omit shop item

### ISSUE THREAD

**Issue by meiomorphism** [FiendsOfTheElements/FF1Randomizer#1035]
The following flagset generates a spoiler log (attached) without a Tail. The Tail _is_ present in the game, however; it's at the Caravan, which happens to be the key-item-bearing shop in this seed.

URL with flagset: https://4-7-2.finalfantasyrandomizer.com/Randomize?s=429DDABF&f=m1-d-T2KF.pumW.V6Z35wSZnFlCPlEwCQISruKVJrYkB06N7JDOKHreN4Q5fiBjild.iyge4E6kpH9nhRZ33hPUwfLJBP-7RD3AYen03cEFMqD5N4PIljX7JVfDiuZHB3lFgBpszuGdsZCYtDaWPfJPm4Ee6emwbbNwehPD

Spoiler log: [Spoiler-2023-11-30-429DDABF_SGNKTSBS.txt](https://github.com/FiendsOfTheElements/FF1Randomizer/files/13537328/Spoiler-2023-11-30-429DDABF_SGNKTSBS.txt)

Procgen map: [FFR_map_A5DB5E106CFBE707E61CBF1ECECC557D.json](https://github.com/FiendsOfTheElements/FF1Randomizer/files/13537358/FFR_map_A5DB5E106CFBE707E61CBF1ECECC557D.json)

**Comment by wildham0** [comment]
Thanks for the bug report, this issue is fixed in 4.7.4.
