### ISSUE TITLE
Deep Dungeon not working in 4.7.8

### ISSUE THREAD

**Issue by ParkaSpace12** [FiendsOfTheElements/FF1Randomizer#1054]
Trying to use the preset Deep Dungeon gets the attached error.
![Error](https://github.com/FiendsOfTheElements/FF1Randomizer/assets/163228654/8b0bf8f7-0073-403b-aba7-035ab9cde745)

Tried 8 seeds, none worked.
Last one tried:
2F32903C

Flags:
m1-hfUk5HrJkqt5PJaPmWLPe-0g0mX7rus8IaGGih0ZChJ8f.DSS9-D8uQZXSiGoDzVOb6RD7ZeD8bAYYQ0vUMNYv36nKLQ9jQGfQfMtQuJZaY0bl78hWkbHVyi063ghSzWb4nICMycladZTVjXk8gqF6s.r2vmfR2XXtgg

Tried to set the same settings in 4.7.7 after seeing the "Improved Vanilla" error, but it just hangs on the second to last step.

**Comment by wildham0** [comment]
Fixed with 4.7.9
