### ISSUE TITLE
Seed Generation Failures with Custom Flags Plus the Mystery of an Unsolvable Seed

### ISSUE THREAD

**Issue by kagerato** [FiendsOfTheElements/FF1Randomizer#1093]
Test Date : 2024 August 18
Test Version : 4.8.3
Flag Set : Custom (see examples below)

It seems some custom flag sets with AirBoat, few shuffled key items, and pregenerated shuffled-access overworlds run into some weird edge cases.   Trying various seed values and map-gen seed selections fairly easily runs into combinations which will fail to generate with error :

"Item placement could not meet incentivization requirements"

Only key items in chests are being shuffled, NPC related shuffles are off.   There in theory should always be enough location slots to fit all items, but in practice I guess there are not ?  When I look through the flags carefully, the only parts that really stand out are AirBoat enabled and the use of the pregenerated but shuffled access overworld.

Here's the first three examples I found which fail to generate this way : 

https://4-8-3.finalfantasyrandomizer.com/?s=C603D50E&f=9Dv8VHGZHxDkHt7YvCNL0KhL4nxAmiCRdU.-PpprgtPTISSdEyHbt-a7H3KZHSLMOrfEAgsDDZSwIO-i8jVRzMVqrOrNVQNvzZwmVBmdMj8jsoRF0enjl2lQnBZY9q2C9w58a92ewodS4wu5LRx9Xk.i.EqX6owEasonFV3cuZWeSOE

https://4-8-3.finalfantasyrandomizer.com/?s=0CCE1E12&f=9Dv8VHGZHxDkHt7YvukhjtKSyd10.F.Uk9JHvc3h1CwzEL8G7M6NHQUhDeUEEFuIBqDhUIPZrTlvrta71jVRzMVqrOrNVQNvzZwmVBmdMj8jsoRF0enjl2lQnBZY9q2C9w58a92ewodS4wu5LRx9Xk.i.EqX6owEasonFV3cuZWeSOE

https://4-8-3.finalfantasyrandomizer.com/?s=AF4799BC&f=9Dv8VHGZHxDkHt7YvucLGR9aMdgZzNEXTVr1KLl-ecL.jv3jqsKOMy27EeF0WR9GqqrbZTA9zlLidqs85jVRzMVqrOrNVQNvzZwmVBmdMj8jsoRF0enjl2lQnBZY9q2C9w58a92ewodS4wu5LRx9Xk.i.EqX6owEasonFV3cuZWeSOE

Perhaps even more interestingly, I played a seed today with value 61326A50 on these same flags, but I foolishly discarded/lost the mapgen seed (and thus don't know which of the pregenerated maps it was, other than having the minimap image of it below) .   That seed generated fine of course, but ultimately looked to be impossible to complete.   Under these flags, Bikke in Pravoka should always have the Ship (as I understand it, anyway) .   However, Pravoka, Temple of Fiends, Ice Cave, and Gaia were all air-or-sea locked isles.  It appears the logic was assuming it was possible to acquire and use Airship, which it would have been except for the AirBoat flag blocking it from being raised from the airship desert.   At one point, I also considered whether it was simply a shipless seed, but that didn't appear possible either (and AFAIK the generator never fully-isolates key items even if they're not actually required to complete the current seed) .

Here's what the pregenerated shuffled-access overworld looked like in seed 61326A50 with the unknown mapgen sub-seed value : 

![world-minimap-tiny](https://github.com/user-attachments/assets/e90c466a-75d3-4d0f-9818-29f0084f59c1)

![world-minimap-scaled](https://github.com/user-attachments/assets/3514421a-2512-4bae-af90-60e423efc2f6)

It was not possible to confirm in-game, but it looks like the ship/airship locked locations were : 

* Gaia on the small island to the north of Temple of Ordeals (at north-mid-center) .
* Ice Cave on the mid-sized subcontinent in the south.
* Pravoka and Temple of Fiends on the small southwestern islands.

Titan's Tunnel led to the eastern-most subcontinent, where only Bahamut and the Oasis were present.

The desert cross where the airship is normally raised was on the main continent (north-central region), but as mentioned AirBoat flag prevented it from being used.  Floater was discovered in a western Cardia cave.  So it might be an odd flags interaction without a specific cross-check led to an unsolvable seed ?

I definitely understand how with the absurd number of combinatorial possibilities that custom flags produce, something could slip through here.

In any event, thanks to everyone who's worked on FFR.  Always a good time (even when I discover our quest is soft-locked three hours in -- lol).

**Comment by wildham0** [comment]
Contrarily to standard procgen ow maps, shuffled access maps don't guarantee early access to pravoka so if you don't shuffle npcs the ship can be simply inaccessible and more often than not you can't beat the seed without it (sometime the airship desert might be on the starting continent and you can raise the airship, but obviously airboat would prevent that from working).

As for the mystery map, logic does account for the airboat setting so it should be beatable, unfortunately i can't do much troubleshooting without the actual map. If you still have the rom, you can run it here and post the info from the textbox:
https://4-8-3.finalfantasyrandomizer.com/rominfo

**Comment by tetron** [comment]
Most "shuffled access" maps are probably not beatable without shuffling NPCs, e.g. if Crescent lake could be canoe locked or ice cave could be airship locked.  What you'd expect to see in those situations is to get "Item placement could not meet incentivization requirements" 100% of the time, so it seems like this is probably a logic checker bug.

If you don't want to shuffle NPCs, then the "standard" procgen maps are the way to go.

**Comment by wildham0** [comment]
when you use the pregen option, there's no map seed so it's fine
i was able to extract the map with that info and you're right it isn't completable with airboat, there was in fact a logic bug

as for the wiki, it's managed by the community discord, so you can suggest changes and improvement over there
thanks for the bug report!
