### ISSUE TITLE
TNT spot may not open on randomly generated maps if Astos is shuffled to TNT dwarf

### ISSUE THREAD

**Issue by PuzzleSecretary** [FiendsOfTheElements/FF1Randomizer#1095]
I am currently playing this seed:

https://4-8-3.finalfantasyrandomizer.com/?s=530429FD&f=G4P6A-JiN4KMx9bq.1awI41JawO-pImJ4tRUlEkb37r1N.sESAHmwssfi6u3NJknLO7GHTuPEEaHk4iU0RYzYotyUBvciikloANpag-euZrxdVUbZNqWvz85B-IIrFiI7X66xS0bpPyFhT0TcM9pq7qlR11xghk2QxNPiU3cuZWeSOE

...and while I got my usual chuckle out of finding out that today Astos was a Dark Dwarf plotting to break into the dwarven vault, and I did get the Crystal when I defeated him, the TNT did not go away... and when I eventually got the Ship, I ran into one port that was blocked by what appears to be the TNT isthmus:

![this-should-be-blown-up](https://github.com/user-attachments/assets/69d452ab-5724-4048-a136-e635588f30f9)

This appears to only block the way to Bahamut, so it's not seed-breaking in this case, but it still seems like something that isn't supposed to happen and could be seed-breaking in other situations.

**Comment by wildham0** [comment]
The digging of the canal is a separate item (CANAL), another npc or a chest will have it, opening the path.
