### ISSUE TITLE
NPC Shuffle - Misc Issue Discussion

### ISSUE THREAD

**Issue by dhmoeller** [FiendsOfTheElements/FF1Randomizer#110]
The following "issues" have been discussed in Discord regarding the NPC shuffle option. Maybe they don't need to be fixed, this thread should be for discussion on which, if any, should be fixed. Specific details of how to fix the issue can break off in a separate item if needed.

- You can only buy 99 HEALs but if you open a chest at that point your total will show in inventory as A0, A1, etc.. In vanilla this was also bugged and simply threw the item away and left the chest empty. Fixing this would probably require moving a method to a new bank so a few more bytes are available to check for quantity 99 and show a "Can't Hold" message or allowing the display in the inventory to show values > 99.
- If you walk across the canal before you walk across the bridge you’ll see the cutscene there instead. This is vanilla behavior but was impossible before map edits.
- The flag string is now too big to fit on the menu screen in game so a shorter ‘hash’ is there instead. Ultimately this will be replaced by the Icon Hash feature anyway (in #82), so a separate fix isn't needed.

**Comment by dhmoeller** [comment]
Another issue has been identified: 
- When caravan item shop slot is not incentivized it can have a `HEAL` or `HOUSE` or other consumable items assigned. When Shop Shuffle is also turned on, that item can be shuffled to a shop containing a duplicate of the same consumable. This isn’t intended but should be pretty rare and limited to specific flagsets.

**Comment by CressCelesta** [comment]
I just rolled a seed that requires a key from the caravan item located in Corneria, but the only locations available are the Corneria and Lazy Dwarves area. It's wholly unreasonable to get 50k+ gold prior to Pravoka area being available. Perhaps blocking the caravan item in Corneria being required with open mode would stop this from being a problem in the future.

**Comment by dhmoeller** [comment]
50K G first progression is definitely not intended! We will take a look and try to hotfix that soon.

This was previously fixed by majorly reducing the price of any item potentially blocking early progression before Elfland. I think at the time of that fix the Key couldn’t be blocking the Ship, so the price of Key was not reduced, but then later on changes were made to allow key-locked Ship without also updating the price of the Key when it gets placed in the first two towns.
