### ISSUE TITLE
Weekly teaching sessions

### ISSUE THREAD

**Issue by Falconic-FF** [FiendsOfTheElements/FF1Randomizer#177]
How do you guys feel about creating/adding a voice channel in discord that people can place themselves into while they practice to indicate that they would like others to watch them and provide real-time feedback on tips/tricks/strategy?

Could expand this into a scheduled weekly event where some of the better runners get together and explain various mechanics such as encounter manipulation, item management, etc..

**Comment by latzio** [comment]
While a good idea - this issue tracker is really designed at FFR software development itself, as opposed to the discord community and the social network aspect of it.

You might want to reach out to to the administration there directly.
