### ISSUE TITLE
Connection not secure

### ISSUE THREAD

**Issue by SmashManiac** [FiendsOfTheElements/FF1Randomizer#193]
finalfantasyrandomizer.com does not support HTTPS.

This causes the following issues:
- Browser warnings. (For example, in Chrome, "Not Secure" appears in the URL bar.)
- Vulnerable to man-in-the-middle attacks to deface the website with ads or inject malware.
- Cannot use HTTP/2 for better performance.

Note: Some CAs can automatically offer and renew TLS certificates for free nowadays, so budget should not be an issue.

**Comment by Entroper** [comment]
Was planning to do Let's Encrypt for this, but if all goes well with #219, maybe we'll just host on S3 and have HTTPS by default.

**Comment by Entroper** [comment]
We're hosted with HTTPS now.  :)
