### ISSUE TITLE
Paste flag fail with 2.3.1 Windows exe

### ISSUE THREAD

**Issue by jkq3** [FiendsOfTheElements/FF1Randomizer#208]
"D0AD7A5B_PACPHUBPYAHFHA!fPUoyyBA" fails to paste in the windows exe with "Format not recognized".

**Comment by drcatdoctor** [comment]
@jkq3 Looks like those are beta flags and there's no beta windows exe at the moment. You'll have to use the website. Reopen/comment if that isn't the case.

**Comment by latzio** [comment]
Yeah the windows app doesn't get the love the website does - the good news is we're about to launch 2.4 and I'll make sure we test the seed/flags pasting. thanks for the bug report.

**Comment by latzio** [comment]
This is now patched in the beta codeline (which we don't ship...) but with the next promotion scheduled for sometime in the next few days it's fixed.
