### ISSUE TITLE
CLI Seed parameter is case sensitive

### ISSUE THREAD

**Issue by bedmonds** [FiendsOfTheElements/FF1Randomizer#221]
# Observed
`FF1R <rom_file> -s deadbeef` explodes, but `FF1R <rom_file> -s DEADBEEF` works fine.

# Expected
FF1R should successfully generate a rom regardless of its users' preference in letter capitalization.

**Comment by Entroper** [comment]
This should be easy enough to fix.  I'm pretty surprised it's broken actually.

**Comment by bedmonds** [comment]
The regex is only checking for A-F and not A-Fa-f.

Incidentally, I'm reworking the CLI a bit which also fixes this issue. 

https://github.com/bedmonds/FF1Randomizer/blob/cli-remake/FF1R/Program.cs

**Comment by bedmonds** [comment]
Fixed in the CLI Remake merge.
