### ISSUE TITLE
CLI parameter handling is non-standard.

### ISSUE THREAD

**Issue by bedmonds** [FiendsOfTheElements/FF1Randomizer#222]
The way the CLI handles option parsing does not reflect the way that options are typically (or can be) supplied.

For single-letter switches with required arguments, it's customary to specify values immediately following the switch, without a space between the two. e.g. `FF1R -fFLAGS` instead of `FF1R -f FLAGS`.

For longer ones, either an equals sign or a space should work identically. e.g. `FF1R --flags=FLAGS` or `FF1R --flags FLAGS`

Currently, only the latter works. Option parsing depends on a pair number of arguments, each separated by spaces, which is unexpected for CLI users, and fails to account for switches without arguments such as `--help` or `--version`.

# Expected Behaviour
`FF1R <rom_file> -f<flags> --seed=<seed>` being functionally identical to `FF1R <rom_file> --flags <flags> -s <seed>`.

**Comment by Entroper** [comment]
So I wasn't going to reinvent the wheel of command line argument parsing, and I just did a quick and dirty implementation.  I found a .NET library that parses standard args, but it didn't support .NET Standard.  I can look again.

**Comment by Entroper** [comment]
This was the original: https://github.com/commandlineparser/commandline
We'll see if this does the trick: https://github.com/natemcmaster/CommandLineUtils

**Comment by bedmonds** [comment]
Fixed with the CLI Remake merge.
