### ISSUE TITLE
Experience overflow causes game to crash

### ISSUE THREAD

**Issue by Invariel** [FiendsOfTheElements/FF1Randomizer#268]
When gaining experience that would push the player past level 50 using the alpha randomizer, the game hangs.

Attached is the seed that I generated from the alpha site, along with a BizHawk 2.3 save file which has me just outside of the Temple of Fiends, a Garland fight away from TOFR, to experience the bug.

[FF1R Alpha Seed + SaveRAM.zip](https://github.com/FiendsOfTheElements/FF1Randomizer/files/3101683/FF1R.Alpha.Seed.%2B.SaveRAM.zip)

**Comment by Steven-Biro** [comment]
This is fixed in alpha now
