### ISSUE TITLE
Coneria just a big forest.

### ISSUE THREAD

**Issue by gnpunk** [FiendsOfTheElements/FF1Randomizer#270]
Trying out randomizer for the first time and no matter what seed I use, Coneria isn't there and is just this huge forest.

**Comment by Steven-Biro** [comment]
I assume you are using the main site, ie not beta.finalfantasyrandomizer.com or alpha.finalfantasyrandomizer.com

Make sure you are using an unmodified US FF1 rom. if you still have this issue, please let me know

**Comment by gnpunk** [comment]
Yes, I'm using the main site and, to the best of my knowledge, it's an unmodified rom.

**Comment by Steven-Biro** [comment]
can you provide the url (it contains the seed and flags) on the randomization page

**Comment by gnpunk** [comment]
Looks like it was a modded file.

Tried a different ROM from another site and this one is working properly.

Thanks for the info!

**Comment by Steven-Biro** [comment]
No problem! Closing this issue now
