### ISSUE TITLE
Suggestion: Add "Sea Shrine (locked)" incentive chest

### ISSUE THREAD

**Issue by bigmalletman** [FiendsOfTheElements/FF1Randomizer#316]
There's a locked door in the Sea Shrine, the crescent shaped room in the center of the floor. Most people never notice it, because you already have the key, but it normally only contains 20 G. In a randomized game, it is a door that is frequently inaccessible when first encountered, but usually contains nothing special. It seems like a good spot for an incentive chest.
![sunken-shrine-4f-c](https://user-images.githubusercontent.com/9523991/70728168-86451c80-1cc6-11ea-8ac5-3d9fde909787.png)

**Comment by wildham0** [comment]
Now doable by selecting "Behind Gating" for sea shrine
