### ISSUE TITLE
Alpha Site Help Text

### ISSUE THREAD

**Issue by Invariel** [FiendsOfTheElements/FF1Randomizer#330]
"Open Northern Progression" is missing help text.
"Static Exp Distribution" - rather is misspelled as rahter.

**Comment by latzio** [comment]
Hey Invariel thanks for the heads up! (I'm nitz)

We're actually decommissioning alpha but I'll make sure these tooltips are in beta.

**Comment by latzio** [comment]
Done! Checkout beta.finalfantasyrandomizer.com for the fixes.
