### ISSUE TITLE
Resetting game within emulator does not progress the encounter table

### ISSUE THREAD

**Issue by hellaplex916** [FiendsOfTheElements/FF1Randomizer#369]
I've watched in randomizer tournaments that resetting can move the encounter table forward to get a longer run before another encounter takes place. However when I reset to move it forward it repeats the same encounter after the same number of steps.  I am using OpenEMU emulator to play the game.

**Comment by one1fineday** [comment]
There is a difference between hard reset (turning power off and on) and soft reset (pushing the reset button).  OpenEmu doesn't allow for a soft reset.

We have a patch waiting in alpha which resolves this issue by allowing a soft reset with up+b on controller 2 (it already allows a hard reset with up+a).  It isn't perfect as you cannot reset when the game is not accepting input (which means no reset if you get ambushed and aren't very fast with the controller).

**Comment by hellaplex916** [comment]
Thank you for the prompt response it’s very much appreciated.  I play through my MacBook Pro and have to use a dongle  to convert to a USB port so I can only use one controller at a time unfortunately.

I guess my last question is are there any emulators in which the reset capability is recognized by the rom to advance the encounter table?   I’ve enjoyed playing this the last few weeks and was just curious if I could get that capability how fast I can get a seed done.

No rush on the answer just curious.

Regardless thanks to you and the developers for creating this randomizer.  The tournaments are super cool to watch it got me into final fantasy (and super Metroid one of my ALL time favorites) again!

**Comment by Isahiro** [comment]
Many emulators allow for soft resetting. FCEUX and Bizhawk, for example, both have the option to map both soft and hard resets. Though I'm unfamiliar with Mac emulators

**Comment by latzio** [comment]
There is nothing here to fix - just need to sort out your hard reset vs. soft reset situation.
