### ISSUE TITLE
Make it easier to use mutliple HEAL potions or spells

### ISSUE THREAD

**Issue by Entroper** [FiendsOfTheElements/FF1Randomizer#39]
Remembering the last cursor position might be the easiest way, ideally just stay on the screen and let the player mash the A button (but we need to keep track of items or spell charges remaining).

**Comment by bedmonds** [comment]
Changing items so that Heal pots are always the first item would be significantly easier; I believe there's a patch floating around in the wild for it.

**Comment by gameboy9** [comment]
From Discord, this was my solution:

0x3B175 -> 20 EE BF... 0x3BFFE = 86 70 / BD 00 03 / 60... 0x3B150 = A5 70

Basically it puts the item cursor into an unused piece of memory, $0070, then recalls it when you go back to the item menu.  The only issue is that the memorized cursor can go into blank space if everything of an item is used.  If you select that space, it does nothing, but you can move the cursor off that space.
