### ISSUE TITLE
Randomized party

### ISSUE THREAD

**Issue by Entroper** [FiendsOfTheElements/FF1Randomizer#47]
Randomly choose (and prevent the player from changing) some or all party members.

The most basic version of this feature would just let the user select a number of party members to be chosen randomly, 0 - 4.

The most advanced version would let the user choose which classes are allowed in each slot, and whether or not that slot is randomized.  This would let the user, for example, disallow Black Belts in the party, or maybe only allow them in one slot at most.  Or you could set the first two slots as fighting classes and the last two as mages, but have them randomly chosen.  Or any number of other combinations.

**Comment by Entroper** [comment]
This is being worked on in #44.

**Comment by latzio** [comment]
It's close now, but any forcing requires randomization instead of being allowed to choose.

**Comment by latzio** [comment]
Done in alpha.
