### ISSUE TITLE
Missing Progression Items

### ISSUE THREAD

**Issue by andyrom52** [FiendsOfTheElements/FF1Randomizer#500]
I'm relatively new to randomizer, so apologies if this is a noob question. I've tried several seeds with different settings, but I keep getting stuck without necessary progression items in any chests or locations available to me.  Twice it's been the floater, once it was a ship (got canoe, did ice cave and everything else, but was stuck on the north continent in the inner sea.)  Any suggestions on what I might be doing wrong with settings?  TIA!

**Comment by latzio** [comment]
This actually shouldn't be possible!

What's most likely is that you're missing somewhere that you can go or something that you can check. If you shuffle shops it's possible that there is a key item for sale in one of the Item Shops that you can get to.

Have you considered asking questions in the community discord? If you post the URL with seed and flags there there are probably 30 people who will play through the seed to help find what you're missing, seriously!

**Comment by highqualityshaun** [comment]
My first experience with FF1R was exactly the same. There is a flag called “open progression” which creates a walking path from the Coneria area you start in to Dwarf cave. You should definitely join the discord and get your questions answered in the “new player duck pond” channel!

**Comment by latzio** [comment]
Likely not a bug in the rando, but a confusing outcome! Consider asking questions like this in the community.
