### ISSUE TITLE
Spaces replaced with +

### ISSUE THREAD

**Issue by Trelior** [FiendsOfTheElements/FF1Randomizer#533]
I finally came back to FFR recently and found a rather humorous, but annoying quirk in the new text modification.

![FFR_6BA6CA54_gqEVHsWinq84KWkJ92 5ecKHVxGvq0CVabjOeXXgNn7FdaVcqs5eciJy5Ab56UP-LRxUxUkDpCsvo-DNumToKdvLs9Xy28D AucC-2](https://user-images.githubusercontent.com/79821178/110280046-27915000-7fa8-11eb-8bb7-7a929bae7739.png)
![FFR_6BA6CA54_gqEVHsWinq84KWkJ92 5ecKHVxGvq0CVabjOeXXgNn7FdaVcqs5eciJy5Ab56UP-LRxUxUkDpCsvo-DNumToKdvLs9Xy28D AucC-3](https://user-images.githubusercontent.com/79821178/110280062-30822180-7fa8-11eb-8cf1-5dca99630b46.png)
![FFR_6BA6CA54_gqEVHsWinq84KWkJ92 5ecKHVxGvq0CVabjOeXXgNn7FdaVcqs5eciJy5Ab56UP-LRxUxUkDpCsvo-DNumToKdvLs9Xy28D AucC-4](https://user-images.githubusercontent.com/79821178/110280197-69ba9180-7fa8-11eb-81cc-897ec94efc07.png)
![FFR_6BA6CA54_gqEVHsWinq84KWkJ92 5ecKHVxGvq0CVabjOeXXgNn7FdaVcqs5eciJy5Ab56UP-LRxUxUkDpCsvo-DNumToKdvLs9Xy28D AucC-5](https://user-images.githubusercontent.com/79821178/110280524-f402f580-7fa8-11eb-8200-cb70cddc1ae1.png)

I've traced the culprit to the symbol being added during the randomization here 
![image](https://user-images.githubusercontent.com/79821178/110280907-a8048080-7fa9-11eb-8ca4-f3d4f58ed2ba.png)

The only modification to my text on the my base ROM is minor spell name edits, monster names, and normalizing the capitalization on items and attacks. Being mindful that an old ROM I had no longer works, and breaks on finalizing the mod, I was careful to preserve the original blank spaces in Hackster.

Please advise. I don't want to have to manually delete the + graphic in every ROM I generate.

**Comment by wildham0** [comment]
So for some reason when you modify text in FFHackster, instead of writing back the text with the space byte $FF, it writes it back with the unused character $C1. So the immediate solution right now is to either manually change the $C1 to $FF or to use another editor to modify the text. I'll see what we can do on our end.

**Comment by wildham0** [comment]
Well, that was easy, should be fixed now.
