### ISSUE TITLE
Character Select Thief Has Floating title Character

### ISSUE THREAD

**Issue by Trelior** [FiendsOfTheElements/FF1Randomizer#540]
Hi, it's me again. The fix for the erroneous + was a huge success! Thank you so much for that! However, the Thief still has an artifact of weird on it on the New Game screen.

![FFR_EF2A50ED_ATAJtVwqlznoyqzu8FvTMCkJg23pCdSZ8VAoU5JzVDq rN8ZVZ4-xZfzjMtxbH5Ol-i68SzEdoz2bLr8Tn7RRjsqbcB0XxKtz8Kq0pb7RDiXeAiNk4mXVN00E-0](https://user-images.githubusercontent.com/79821178/111021091-0cec1c00-8398-11eb-9f95-9417d1aa02ec.png)

Everything else looks peachy keen. I even looked in Hackster, it's a space in the base ROM, but the space is removed in the shuffled ROM. Is this an artifact of Thief Fix? The flags I used don't even have that selected.

**Comment by wildham0** [comment]
I can't reproduce this and the thief fix doesn't touch the class name, you can link the flagset you're using, but it seems more to be a problem with the rom hack than with the randomizer (it should be 2 spaces after "Thief", no just one).

**Comment by Trelior** [comment]
The 4.1.1 flag string is A4Ig2fmmkzv2k3LVvJEUbdB7IfMHP9T40tVaLdpeHYDlCUqHswfvLfYAjkBKYVX0RzuCSmBtEzd0dk3i4fJjkn76osfn32Ktz8Kq0pb7RDiXeAiNk4mXVN00E

When I made the change to the ROM, I could have sworn I preserved the proper amount of spaces.

**Comment by wildham0** [comment]
One things I might see is that you saved the class names by using DTE (if the View With DTE box is enabled), which could be throwing off the randomizer, you could try resaving the names by disabling View With DTE.

**Comment by Trelior** [comment]
If anything, that actually made it worse. Now my Thief on the selection screen is called a "Thiefer"

![FFR_5D8D73DB_A4Ig2fmmkzv2k3LVvJEUbdB7IfMHP9T40tVaLdpeHYDlCUqHswfvLfYAjkBKYVX0RzuCSmBtEzd0dk3i4fJjkn76osfn32Ktz8Kq0pb7RDiXeAiNk4mXVN00E-0](https://user-images.githubusercontent.com/79821178/111082252-ad982400-84dd-11eb-8472-f7e320b6ae3f.png)

I would mod the game from scratch again, but it's a lot of work. If I knew how to "properly" edit the text zones, I would. I don't know of other utilities to use, and using a hex editor makes no sense because I can't visualize what any of it means.

**Comment by wildham0** [comment]
Fixed
