### ISSUE TITLE
Shop Info for spells is incorrect/misleading

### ISSUE THREAD

**Issue by Steven-Biro** [FiendsOfTheElements/FF1Randomizer#561]
Shop info does not take into account resists when showing damage
fir3 should have 50 as the low end and lit 3 60

![fire3](https://user-images.githubusercontent.com/14033941/112736840-278fca80-8f2c-11eb-84a7-f7d8fa1b28f4.png)
![lit3](https://user-images.githubusercontent.com/14033941/112736841-28286100-8f2c-11eb-92e6-05b0f5e41231.png)

**Comment by Steven-Biro** [comment]
Potential fixes include saying what the resisted damage is too, including the resisted low end in the range, or making it clear in the tooltip that it does not include resisted rolls in the damage range

**Comment by wildham0** [comment]
ShopInfo now show weakness and resist values for damage spells
