### ISSUE TITLE
Page is stuck

### ISSUE THREAD

**Issue by MystBunny** [FiendsOfTheElements/FF1Randomizer#742]
![image_2021-10-06_12-46-44](https://user-images.githubusercontent.com/79949095/136255965-bf3ad64a-2194-46b7-a70e-f63df782a89a.png)

This is all I'm getting. I've refreshed many times and waited about an hour.

**Comment by tetron** [comment]
It is probably failing to start for some reason.

1. Check the browser console.  This is F12 on both Firefox and Chrome
2. Try a different browser
3. How much RAM does your computer have?

**Comment by wildham0** [comment]
what your firefox version? it seems to be an issue with older versions of firefox
