### ISSUE TITLE
Trapped Treasure Chests

### ISSUE THREAD

**Issue by Entroper** [FiendsOfTheElements/FF1Randomizer#76]
This feature makes treasure hunting a bit more like later FF games, where instead of map tiles being trapped, the treasure chests are trapped instead.

* Trapping map tiles in front of treasure chests is just janky.
* Weird things can happen, like accidentally (or intentionally) fighting the FIENDs in ToFR multiple times.
* It just feels wrong having to fight the same trapped tile twice, like the GARGOYLEs in NE ToF, or the AGAMA in front of the Red D in Volcano, or the Frost Ds in Ice Cave.
* Trapped chests will trigger an encounter when you try to open them.  Only after you defeat the encounter (you must win, not run) will you learn the contents of the chest.  The easiest implementation would just set (or clear) another treasure chest bit and stick you back on the map, where you can now open the chest yourself.
* A lot of the trapped tiles guard more than one chest, or guard entire rooms.  Some of these, we can convert to NPCs, like the PHANTOM and FIENDs in ToFR.  For others, we might trap just one chest, or several.  Trapping a door has been suggested, but this seems trickier than other options.  We'll have to just use good judgement to determine which chests to trap with which encounters.  It's not going to map perfectly to the original trapped tiles in all cases.
* Not sure what to do about the Hall of Giants.  Could leave it trapped, or we could clear it out.  No one ever seems to go there, anyway.  Part of the idea of removing trapped tiles is to eliminate easy grind spots like the AGAMAs in Volcano.  HoG probably isn't a great grind spot anyway.

**Comment by tetron** [comment]
We have monster in a box now, maybe this can be resolved?
