### ISSUE TITLE
Loose item in incentivized dungeon, despite flag

### ISSUE THREAD

**Issue by meiomorphism** [FiendsOfTheElements/FF1Randomizer#794]
https://beta-008525ad.finalfantasyrandomizer.com/?s=293FB545&f=IhgcHODSbeRP6u375W6Hv0T831vkuUZmq91H62lvN2murChNNS97f6IBNU6g4NO2384XRltIKZDnkojyPkB66O4bTeDLCinLJq17ZaTXuUUqg0GfQpXPyNvp6HXWXyIP3Tel52CGWkYMYN1m8mjN8sgEQC1V

Despite the "No Loose Items in Incentivized Dungeons" flag being checked, the Marsh Cave contains both the BOTTLE and CRYSTAL, as well as the CANOE in the locked area. (Both Marsh Cave incentive location flags were checked, so exactly two items were expected.)

Relevant spoiler log lines:
```
Bottle      MarshCaveTop -> MarshCaveTop -> MarshCave7                  ()
Canoe       MarshCaveBottomRoom16 -> MarshCaveBottomRoom16 -> MarshCave13 (Key)
Crystal     MarshCaveTop -> MarshCaveTop -> MarshCave8                  ()
```

**Comment by wildham0** [comment]
It seems predictive placement isn't 100% compatible with no loose items, thanks for reporting

**Comment by wildham0** [comment]
Fixed in beta
