### ISSUE TITLE
ROM Hashing

### ISSUE THREAD

**Issue by Entroper** [FiendsOfTheElements/FF1Randomizer#82]
Ideally we'd like to hash parts of the ROM, but not all of it (to allow people to use fun graphics patches like FF Valkyries, FF3j tilesets, etc.).  Then based on the hash, we can display a series of sprites on the title screen that are easily recognizable and verifiable on stream.  This is not bulletproof, but it helps ensure the integrity of the ROM.

**Comment by latzio** [comment]
Tournament mode kinda does this.
