### ISSUE TITLE
Improved Vanilla Preset has some unintentional flags set

### ISSUE THREAD

**Issue by Yoshi348** [FiendsOfTheElements/FF1Randomizer#830]
The Improved Vanilla Preset still has Exp Chest Conversion set to 20%, which is probably very much unintended. Treasure chest stacks are also set to Adequate, which I think is unintended, though someone could argue it's QoL.

**Comment by tetron** [comment]
Yea, those are mistakes, thanks for pointing it out!

**Comment by wildham0** [comment]
Fixed in beta, will reach live site next time it's updated
