### ISSUE TITLE
improved vanilla preset has EXP chests

### ISSUE THREAD

**Issue by tetron** [FiendsOfTheElements/FF1Randomizer#920]
This happened by accident, apparently due to a bug in the sliders causing the setting to carry over from the beginner preset.  It has since been fixed, but improved vanilla hasn't been updated.

**Comment by DarkTwinge** [comment]
It's not set on either beta or live currently for Improved Vanilla on my end.  (If it showed up for you, was it because you clicked the preset button before the site finished loading?)

**Comment by tetron** [comment]
A user reported it but I think they might have had an older version bookmarked.  I got confused because the EXP chest reward was non-zero but I think you fixed it in another branch to disable that when chest conversion is 0%
