### ISSUE TITLE
Malus "No Promoted Armor" bugged

### ISSUE THREAD

**Issue by lenophis** [FiendsOfTheElements/FF1Randomizer#949]
Played a seed tonight on 4.6.1, https://4-6-1.finalfantasyrandomizer.com/?s=9F3C5285&f=mHr6T.nxrYLISOcPzkYLwArav5j.nVzQ18IQOUBq938dcY9OUDeuXOIeW5Z-zJ4MlOA4KCXmr4MkvRcTPIl8IL7br3iuH81odT3opEwmBFvuUrjOMnPTUJHhmvA0HKDnZBkaG0JRswb8W1mDowhRGzsdIRpVtYlSEcjQW
specifically.

Fighter drew "No Promoted Armor" as the malus. Once fighter promoted, he was no longer able to wear the ProRing, despite it being an all classes piece. He was also not able to equip the ribbon for the same reason.

Upon further inspection once the seed was completed, the knight was not able to wear any piece that was listed "All Classes," so that is every bracelet, the ribbon, and the proring. The fighter was able to wear all of these pieces before promotion.

The malus seems to be doing its order of operations incorrectly in this case.

**Comment by DarkTwinge** [comment]
Will be fixed in the next release - thanks for the report!
