### ISSUE TITLE
Earth Shirt [Armor crafter] not wearable by Thief w/ Equip Shirt blessing

### ISSUE THREAD

**Issue by sapphirecat** [FiendsOfTheElements/FF1Randomizer#975]
Just what the title says.  My thief has +Equip Shirt blessing, but I found a shirt that's not equippable.

* FFR 4.6.4
* seed 7F24675A
* flags 22WS.hoO5Fj0MVZoocS2YHWNWPJDGB41JQUkjQ5eUBDYbUlnTihD3NzCKh8CHXfEUHTZtrfi2W.Z2PD81bOXmfLOZz1DQhl4uLUuHUg0ksGXR.VxDjhfyJRztUlF.uMvDzR7bs6mFiH3OQkkHA87.H64kDxTBbBFA6LKr

IIRC, that's just the Over Randomizer preset.

Screenshots comparing Burlap, Black, and Earth (the one missing Th) shirts, plus Thief's stat screen:

![FFR_7F24675A_22WS hoO5Fj0MVZoocS2YHWNWPJDGB41JQUkjQ5eUBDYbUlnTihD3NzCKh8CHXfEUHTZtrfi2W Z2PD81bOXmfLOZz1DQhl4uLUuHUg0ksGXR VxDjhfyJRztUlF uMvDzR7bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_003](https://user-images.githubusercontent.com/325537/215292964-38c00923-a48e-49d1-8b38-e8455eb4840f.png)
![FFR_7F24675A_22WS hoO5Fj0MVZoocS2YHWNWPJDGB41JQUkjQ5eUBDYbUlnTihD3NzCKh8CHXfEUHTZtrfi2W Z2PD81bOXmfLOZz1DQhl4uLUuHUg0ksGXR VxDjhfyJRztUlF uMvDzR7bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_000](https://user-images.githubusercontent.com/325537/215292965-bfa462d5-37cf-4882-b9b2-bdb1c7f7627e.png)
![FFR_7F24675A_22WS hoO5Fj0MVZoocS2YHWNWPJDGB41JQUkjQ5eUBDYbUlnTihD3NzCKh8CHXfEUHTZtrfi2W Z2PD81bOXmfLOZz1DQhl4uLUuHUg0ksGXR VxDjhfyJRztUlF uMvDzR7bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_001](https://user-images.githubusercontent.com/325537/215292966-99e3c04e-f88c-427a-8f69-61e9af3c5445.png)
![FFR_7F24675A_22WS hoO5Fj0MVZoocS2YHWNWPJDGB41JQUkjQ5eUBDYbUlnTihD3NzCKh8CHXfEUHTZtrfi2W Z2PD81bOXmfLOZz1DQhl4uLUuHUg0ksGXR VxDjhfyJRztUlF uMvDzR7bs6mFiH3OQkkHA87 H64kDxTBbBFA6LKr_002](https://user-images.githubusercontent.com/325537/215292967-18558d42-07cc-4d35-a048-c8e20d2e4040.png)

I confirmed the game does not allow thief to equip the shirt anyway; the description is accurate.

**Comment by highqualityshaun** [comment]
thanks for the report

very well written bug report with screenshots, much appreciated

this is mended on beta which will eventually go live after the current community tournament
