### ISSUE TITLE
Scripted Preset Deployment to File

### ISSUE THREAD

**Issue by marcusfox** [FiendsOfTheElements/FF1Randomizer#984]
Is it, or would it ever be possible to generate a rom from a manmade preset via an API or CURL call? I am building a living-room emulation system and would love the ability to generate a random tournament or deep dungeon rom from a simple executable or batch file, without the need to breakout the mouse and keyboard and go online to the site to run it.

**Comment by highqualityshaun** [comment]
if you pull the project the webUI version isn't required to generate seeds, you could use the CLI to generate them if you still wanted. an API or CURL call might be out of the scope of this project

generate many of the same presets in a loop:
`ff1r presets add presetname <flagstring>
for /l %x in (1, 1, 10) do ff1r generate ff1.nes -p presetname`

or generate a single seed:
for /l %x in (1, 1, 10) do ff1r generate ff1.nes -f <flagstring>

**Comment by marcusfox** [comment]
Thank you! This is exactly the super helpful comment I was hoping for.
