### ISSUE TITLE
Deep Dungeon (Fiend Orbs) & w/ Short ToFR makes dead ends

### ISSUE THREAD

**Issue by highqualityshaun** [FiendsOfTheElements/FF1Randomizer#988]
https://beta-f35bcd7c.finalfantasyrandomizer.com/?s=455FCBDC&f=GgMWICPTpsRYcVEQmiv3lXaD9nJY3DtJiNU-7Kh4laaSqYrSV60puAOZrh7mZS1lvinr1d-SgeBw2T5FDVa2iav-s0UHSe7Fo3SUXX2gqRwkn0Q.z1D1DWuJJo3yd4deZPC3s.s0nfKxhaQxhQ6-oqc2F0JIzUJKYhLX4j

Deep Dungeon mode with Fiends Orbs
Short ToFR
kill Lich Orb (top left), enter staircase
leads you to final boss room but you're on the ceiling. cannot break lute plate or check chests, can only retreat to the start

![DD_Lich_Shortcut_ShortToFR_01](https://user-images.githubusercontent.com/8323547/221640003-2754f256-6542-4121-9888-dc703cab109f.png)

Later when you enter floor 52 from 51 descending normally, you land in between the fiend tiles
if you attempt to go north, the LUTE plate cannot be broken from below, so the 7 chests in that room are unreachable

![DD_Lich_Shortcut_ShortToFR_02](https://user-images.githubusercontent.com/8323547/221640237-16cb10df-949d-4982-894e-76c1ff9932f5.png)

**Comment by wildham0** [comment]
Fixed in beta
