### ISSUE TITLE
Relocate Chests can spawn SHIP incorrectly

### ISSUE THREAD

**Issue by highqualityshaun** [FiendsOfTheElements/FF1Randomizer#990]
Relocate Chests will pool a few maps together and shuffle those chests among the locations, example of a grouping:
{ MapId.ConeriaCastle1F, MapId.ConeriaCastle2F, MapId.ElflandCastle, MapId.NorthwestCastle }

For a flagset where the SHIP can be found in a relocated box, it's possible that the SHIP is interpreted to be in a box that lives in Coneria Castle when placing the SHIP on the overworld.

It is unclear if this has potential to softlock, but it is disorienting to find SHIP in northwest castle, but your SHIP spawns in the Coneria dock. Expected behavior: SHIP spawns in the closest dock location from where it was found.

Seed example:
https://4-6-4.finalfantasyrandomizer.com/?s=4F757451&f=KKFEMuHMCGCxsfREg-.s7jks2VavlsjyvC.qAqPZuMat05wc9Q8Xz7Q.mxlnbNlSXzAH-1sagb9Q4v1.UWE3RLyUHl.wMcI9M9wtj3mP3rXcyLWZeTbiWrIf3vRKwbbWV93eZs4dGHkbILf20-NpohCVcDxTBbBFA6LKr

![relocate_chests_ship01](https://user-images.githubusercontent.com/8323547/222858379-716f9ca3-6066-4a47-af29-11b39a8c33e2.png)

![relocate_chests_ship02](https://user-images.githubusercontent.com/8323547/222858398-b1b4f2cb-e8cf-463a-9a44-da874b3bd0ab.png)

**Comment by wildham0** [comment]
Fixed in beta
